# Generated by Django 5.1 on 2026-08-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='users_otp_is_veri_5d8bc4_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password Reset')], default='signup', max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['purpose', 'is_verified', 'is_used'], name='users_otp_purpose_19513e_idx'),
        ),
    ]
