# Generated by Django 5.1 on 2026-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_otp_users_otp_is_veri_5d8bc4_idx_otp_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='users_otp_purpose_19513e_idx',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='purpose',
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['is_verified', 'is_used'], name='users_otp_is_veri_5d8bc4_idx'),
        ),
    ]
