# Generated by Django 5.1 on 2026-08-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Apartment', 'Apartment'), ('Others', 'Others')], max_length=20),
        ),
    ]
