# Generated by Django 5.1 on 2026-08-17 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_gender_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_primary',
            new_name='is_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='strap_type',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_price',
        ),
        migrations.AddField(
            model_name='product',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to='products.productimage'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_images',
            field=models.ManyToManyField(related_name='variant_images', to='products.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
