# Generated by Django 5.1 on 2026-08-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_is_primary_productimage_is_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coupon_code',
        ),
    ]
