# Generated by Django 5.1 on 2026-08-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productvariant_variant_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
            preserve_default=False,
        ),
    ]
